import { Anton } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  style: "normal",
});

const geistSans = {
  variable: "font-geist-sans",
};

const geistMono = {
  variable: "font-geist-mono",
};

export const metadata: Metadata = {
  title: "Hyle Faucet App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
